background_opacity 0.7

dynamic_background_opacity yes

# Map a key to set opacity to 100%
map kitty_mod+b>1 set_background_opacity 1.0

# Map a key to set it back to your default
map kitty_mod+b>0 set_background_opacity default

# OR: Use a single toggle if you want to cycle (0.1 increments)
map kitty_mod+b>t set_background_opacity +0.2
map kitty_mod+b>r set_background_opacity -0.2
