decoration {
    rounding = 10
    dim_around = 0.8
    # active_opacity = 1
    # inactive_opacity = 0.8
    blur {
        enabled = true
        size = 2
        passes = 3
    }
    shadow {
        enabled = true
        range = 20
        render_power = 4
        offset = 5 5
        color = rgba(1a1a1a88)
        color_inactive = rgba(00000000)
    }
}
