
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

#? ------- WINDOWRULES_HYPRLAND_V_0_53 COMPATIBLE ----------------
#   This Config is compatible with windowrules changes in Hyprland v0.53+
#   Any future breaking changes disables this block and notifies the user to update.
#   User template files will be provided in $XDG_DATA_HOME/hyde/templates/hypr/windowrules.conf for manual update. 


windowrule {
  name = decorate-pinned
  match:pin = true
  border_size = 10
  border_color = $red
}

windowrule {
  name = decorate-focused
  match:focus = true
  border_color = $green $blue  45deg
}

windowrule {
  name = decorate-others
  match:focus = false
  match:pin = false
  border_color = $red
}

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur true,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi

layerrule = blur true,match:namespace notifications
layerrule = ignore_alpha 0,match:namespace notifications

layerrule = blur true,match:namespace swaync-notification-window
layerrule = ignore_alpha 0,match:namespace swaync-notification-window

layerrule = blur true,match:namespace waybar
layerrule = ignore_alpha 0,match:namespace waybar
