#? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

# Assign apps
$TERMINAL = kitty
$EDITOR = vscodium
$EXPLORER = dolphin
$BROWSER = firefox
$GTK_USE_PORTAL=1

source = themes/everforest.conf # Color Theme
source = conf.d/*.conf # My confs
source = monitors.conf # Monitors settings
